# Generated by Django 4.1.7 on 2023-04-07 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('releasedDate', models.DateField()),
                ('genre', models.CharField(max_length=255)),
                ('lyricist', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('arranger', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('lyrics', models.TextField()),
                ('albumImg', models.CharField(max_length=255)),
                ('youtudeId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('love', models.FloatField()),
                ('joy', models.FloatField()),
                ('passion', models.FloatField()),
                ('happiness', models.FloatField()),
                ('sadness', models.FloatField()),
                ('anger', models.FloatField()),
                ('loneliness', models.FloatField()),
                ('longing', models.FloatField()),
                ('fear', models.FloatField()),
                ('surprise', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MusicEmotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('love', models.FloatField()),
                ('joy', models.FloatField()),
                ('passion', models.FloatField()),
                ('happiness', models.FloatField()),
                ('sadness', models.FloatField()),
                ('anger', models.FloatField()),
                ('loneliness', models.FloatField()),
                ('longing', models.FloatField()),
                ('fear', models.FloatField()),
                ('surprise', models.FloatField()),
                ('musicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SongEmotion', to='mixmind.musicinfo')),
            ],
        ),
    ]
