# Generated by Django 4.1.7 on 2023-05-11 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mixmind', '0002_useremotion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPlayList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlayList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('music_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPlayList', to='playList.userplaygroup')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MusicPlayList', to='mixmind.musicinfo')),
            ],
        ),
    ]
